### ISSUE TITLE
Can't find type def files for babel__*, istanbul-*, yargs-*

### ISSUE THREAD

**Issue by dylanh724** [yonathan06/fastify-typescript-boilerplate#1]
Cloned >> `npm i` >> `npm run build` >> type def errs:
![image](https://user-images.githubusercontent.com/8840024/109391233-09e13c80-7951-11eb-8aa5-b4845fd52af6.png)

**Comment by dylanh724** [comment]
## Workaround
Add the following to tsconfig.json -> compilerOptions:
![image](https://user-images.githubusercontent.com/8840024/109391320-6e9c9700-7951-11eb-8fbc-ac2a0c9f19e1.png)

There's probably a better way?

**Comment by yonathan06** [comment]
Can't reproduce. Try deleting `node_modules`, run `npm install` and `npm build` again
